### ISSUE TITLE
Cloning repository with Git in Dockerfile

### ISSUE THREAD

**Issue by Lirt** [postfwd/postfwd#10]
Hello Jan,

Thank you for bringing docker support for `postfwd`.

Today I found out, that DockerHub builds are executed in context of a branch in GitHub repository.

More clearly said, during building you are already located in [this](https://github.com/postfwd/postfwd) cloned git repository in branch specified in DockerHub build.

That means, we don't need to install `git` and execute `git clone` to get this repository. Everything, that is needed is to copy postfwd files to proper locations.

For example these commands should work (I didn't test them all):

```dockerfile
# Copy whole repository to /opt/postfwd
COPY . /opt/postfwd/
# Copy only binaries to proper places
COPY ./sbin/ /usr/sbin/
COPY ./bin/ /usr/bin/
COPY ./tools/postfwd-client.pl /usr/local/bin/
...
```

Also we eventually don't need to copy all files but only things, that can be proficient for user. Maybe binaries from `sbin` `bin` and `tools` and directly to some `PATH` directories?

**Comment by jpkessler** [comment]
Hi Ondrej, good finding - sounds much better than the "git-loop"! Let me check this.

May I mention you in the Changelog with a little "thank you"? And if so, which Name shall I use?

Btw: A new major version postfwd3 is on the way. See the testing-branch for more info.

**Comment by Lirt** [comment]
If you want so, I guess `Lirt <ondrej.vaskoo@gmail.com>`, is someone wants to blame me :D.

Yes I saw something, I am following the news on this repository :-).

**Comment by jpkessler** [comment]
ok, done. i think that we don't need anything except `sbin/` and `etc/` inside the container. would be interested in your opinion about `docker/Dockerfile-autobuild` in `testing`-branch.

**Comment by Lirt** [comment]
I agree. It looks good and cleaner now :-).

**Comment by jpkessler** [comment]
Cool. Thanks!
