### ISSUE TITLE
Quick Start Guide Issues with postfwd2

### ISSUE THREAD

**Issue by David00** [postfwd/postfwd#15]
Hi there,

This report is a 2-part report. First I include my troubles with getting the latest postfwd version installed via apt-get, and then I describe an issue I'm having after abandoning the apt-get installation and trying to run the postfwd1 tarball.  I hope the first part of this helps trace down any issues that may exist, and I'm also hoping you can provide guidance on the issue in the second half. This is a production system so unfortunately I'm not able to provide much troubleshooting assistance, but I'd be happy to clone my production system onto a new sandbox vm and troubleshoot it with you if needed.  Anyways... here is my report:

I just went through the quickstart guide and ran into some problems on my Ubuntu 18.04.1 server.

> $ postconf -d | grep mail_version
> mail_version = 3.3.0

First off, I went for the easy installation method of apt-get postfwd.  This seemingly installed postfwd2 which is probably the start of my problems (my mail server is small and I don't think I need the robust capabilities of postfwd2):

> $ postfwd -V
> postfwd2 1.35 (Net::DNS 1.1, Net::Server 2.009, Sys::Syslog 0.35, Time::HiRes 1.9741, Storable: 2.62, Perl 5.026001 on linux)

I opted to create the postfwd user/group and went with a very simple configuration as shown by the examples. The configuration is not the source of my problems. (Of course I will share if necessary, though)

I can start postfwd no problem:
From /var/log/mail.log...:
> Jan  9 21:01:12 mydomain postfwd2/master[2109]: postfwd2 1.35 starting
> Jan  9 21:01:20 mydomain postfwd2/master[2110]: postfwd2 1.35 starting
> Jan  9 21:01:24 mydomain postfwd2/master[2113]: postfwd2 1.35 starting
> Jan  9 21:01:24 mydomain postfwd2/master[2114]: Started cache at pid 2115
> Jan  9 21:01:24 mydomain postfwd2/master[2114]: Started server at pid 2116
> Jan  9 21:01:24 mydomain postfwd2/cache[2115]: ready for input
> Jan  9 21:01:24 mydomain postfwd2/policy[2116]: ready for input

However, I tried to send a message from a domain that should be permitted based on my config, and I saw the following in the logs:

> Jan  9 20:42:03 mydomain postfix/smtpd[1391]: warning: connect to 127.0.0.1:10040: Connection refused
> Jan  9 20:42:03 mydomain postfix/smtpd[1391]: warning: problem talking to server 127.0.0.1:10040: Connection refused
> Jan  9 20:42:04 mydomain postfix/smtpd[1391]: warning: connect to 127.0.0.1:10040: Connection refused
> Jan  9 20:42:04 mydomain postfix/smtpd[1391]: warning: problem talking to server 127.0.0.1:10040: Connection refused
> Jan  9 20:42:04 mydomain postfix/smtpd[1391]: NOQUEUE: reject: RCPT from mail-oi1-f171.google.com[209.85.167.171]: 451 4.3.5 <support@mydomain.com>: Recipient address rejected: Server configuration problem;...
> 

Postfwd is not listening on 10040. (UFW is disabled so this is not a firewall problem):

> $ netstat -an | grep postfwd
> unix  2      [ ACC ]     STREAM     LISTENING     4226293  /var/tmp/postfwd2-cache.socket
> $ netstat -an | grep 10040
> $

I ended up apt-get purging postfwd and manually installing the postfwd-1.38 tarball.  That appears to be functional - I see port 10040 is open and I can receive mail from the domain that was previous being denied. However, postfwd is complaining about the following when receiving mail:

> postfwd[2681]: warning - "Use of uninitialized value $cacheid in hash element at /usr/local/postfwd/sbin/postfwd line 2257.?"
> postfwd[2681]: warning - "Use of uninitialized value $cacheid in hash element at /usr/local/postfwd/sbin/postfwd line 2257.?"
> postfwd[2681]: warning - "Use of uninitialized value $cacheid in hash element at /usr/local/postfwd/sbin/postfwd line 2261.?"
> postfwd[2681]: warning - "Use of uninitialized value $cacheid in hash element at /usr/local/postfwd/sbin/postfwd line 2262.?"

**Comment by jpkessler** [comment]
Hi, to reproduce this, it would be good to have

1. the ruleset
2. the arguments you used to start postfwd (when using the debian package this should be in `/etc/default/postfwd`)

**Comment by David00** [comment]
Jan, sure thing. Here is my ruleset (/etc/postfwd.cf)
```
# reject if sender equals recipient
#id=RULE-02 ;  sender==$$recipient ;  action=REJECT not allowed

# check some rbls and reject, if listed on >= 2 of them
id=RULE-03 ;  rbl=zen.spamhaus.org,bl.spamcop.net,ix.dnsbl.manitu.net ;  rblcount>=1 ;  action=REJECT not allowed 
```

So I checked /etc/default/postfwd and it doesn't exist. Maybe it was removed when I purged postfwd? I do know that when I was trying the debian package, I started postfwd with (according to the quick start guide):
>postfwd --daemon -f /etc/postfwd.cf -u postfwd -g postfwd

**Comment by Lirt** [comment]
Hello,

Yes `apt-get purge` removes all package files. 

If you used `postfwd` from release without using `systemd` or `init`, then `/etc/default/postfwd` doesn't do anything.

Also make sure user and group `postfwd` exists, because debian package configures user and group as `postfw` (notice missing `d`).

**Comment by David00** [comment]
Thanks Jan and Lirt.

Here is the netstat:

> $ sudo netstat -antupl | grep postfwd
> [sudo] password for ______: 
> tcp        0      0 127.0.0.1:10040         0.0.0.0:*               LISTEN      2681/postfwd.pid    
> tcp        0      0 127.0.0.1:10045         0.0.0.0:*               LISTEN      2116/ postfwd2::pol 


I'm glad my report helped, but I think I was perhaps unclear in my first report. The primary issue was that the quick start guide did not work for me (using apt-get install postfwd) because apt-get seemingly installs postfwd2.  I don't know how the repository is managed, but my apt-get packages all come from the digitalocean repos since my machine is currently hosted with them.  I would suspect if you go through the quick start guide on a clean install, you would run into the same problem of:
>postfix/smtpd[1391]: warning: connect to 127.0.0.1:10040: Connection refused

**Comment by jpkessler** [comment]
Your netstat looks as now you have both versions running (postfwd1@tcp/10040 and postfwd2@tcp/10045) :)

I will repoduce the issue with the quick start guide in an vm. I don't use the packages, but I thought that they include the following setting in `/etc/default/postfwd`?

    # Port where listen to
    PORT=10040

**Comment by jpkessler** [comment]
1.) Updated the quickstart guide as follows (note the "-p 10040"):

**Launch postfwd** 
Start postfwd with your ruleset. Leave out the --user and --group options, if you have skipped step 3 and want to run postfwd as nobody/nobody.

	  # postfwd --daemon -f /etc/postfwd.cf -u postfwd -g postfwd -p 10040

2.) Just pushed v1.39, fixing the issue above with v1.38. It disables AutoCacheID for now. This feature has to be redone completely. At current state it interferes with rulesets containing only postfwd-items (like your case) and possibly with some plugins, too.
