### ISSUE TITLE
Use of uninitialized value $myval if client has IPv6

### ISSUE THREAD

**Issue by jirit** [postfwd/postfwd#22]
Environment:
Debian9
postfwd3 2.01 (Net::DNS 1.07, Net::Server 2.008, NetAddr::IP 4.079, Digest::MD5 2.54, Sys::Syslog 0.33_01, Time::HiRes 1.9733, Storable 2.56_01, Perl 5.024001 on linux)

Hi, 

I just testing postfwd3. I have found this warnings in logs when client has IPv6 address:

 warning: Use of uninitialized value $myval in string eq at /usr/sbin/postfwd line 1681.?
 warning: Use of uninitialized value $myval in string eq at /usr/sbin/postfwd line 1619.?

Over IPv4 is it ok.

**Comment by jpkessler** [comment]
Hi, could you check v2.02? Thx, jpk

**Comment by jirit** [comment]
Hi, seems fixed. Thanks a lot.
