### ISSUE TITLE
How can say: recipient != file:/path/to/list

### ISSUE THREAD

**Issue by sparse91** [postfwd/postfwd#25]
Hi
Is there any way to tell postfwd do something like "item not in file" or Is there any anti-action like thing?
Or at least can you guide me to patch the code for this. I could not find the place. :)
Thanks

**Comment by jpkessler** [comment]
Yes, use sth like this:

id=R001
   sender == file:/some/where
   action=set(GOODSENDER=1)

id=R002
   GOODSENDER==1
   action=dosomething
  
**Please note that this is not the right place for configuration questions. Please use the contact information at postfwd.org for such terms. Thank you.**
