### ISSUE TITLE
Allow parsing or reading RBL TXT data

### ISSUE THREAD

**Issue by mjpcomp** [postfwd/postfwd#29]
It would be great to be able to take the TXT data returned from a query and use that to process rules, or, make scoring adjustments.

For example, if we're using an RBL that returns AS information, it would be nice to take that AS info and adjust a score upwards/downwards. Or, to read that TXT reply for a name or other information.

**Comment by jpkessler** [comment]
You can already do that with a little trick:

DNSBLS {
        rbl=zen.spamhaus.org
        rbl=list.dsbl.org
        rbl=bl.spamcop.net
}

id=RBL_001
	&&DNSBLS
	rhsblcount=all ; rblcount=all
        action=set(HIT_dnsbls=$$rhsblcount,HIT_dnsbls+=$$rblcount,DSBL_text=$$dnsbltext)

id=RBL_002
    DSBL_text =~ /something/
    action=dosomething
