### ISSUE TITLE
Generic configuration of per-user blacklists

### ISSUE THREAD

**Issue by zzyzwicz** [postfwd/postfwd#30]
Does anyone know how to create a generic rule for individual per-user blacklists?
I think about something like:

sender==lfile:/etc/postfwd/blacklists/$$recipient
action=REJECT

which does not work unfortunately.

**Comment by jpkessler** [comment]
**Please note that this is not the right place for configuration questions. Please use the contact information at postfwd.org for such terms. Thank you.**
