### ISSUE TITLE
add sfp check 

### ISSUE THREAD

**Issue by mshabou** [postfwd/postfwd#31]
are there a way to add sfp check on condition ?
the goal is to implant condition traitement if SFP check is OK or KO

**Comment by jpkessler** [comment]
I guess you mean SPF (sender policy framework). No postfwd does not have builtin SPF support. You are free to develop a plugin for that.

**Please note that this is not the right place for configuration questions. Please use the contact information at postfwd.org for such terms. Thank you.**
