### ISSUE TITLE
Integration with LDAP

### ISSUE THREAD

**Issue by imanudin11** [postfwd/postfwd#33]
Hello,
Is it possible to integrate with LDAP? the goal is to query email or domain from existing LDAP. And using some filters to gather email/domain. I usually use lfile or ltable. The example maybe like this

before
sender=ltable:/path/to/query/configuration.cf

after
sender=ldap:/path/to/query/configuration.cf

So, I am not necessary to input email/domain on ltable file. All query will be automatically by LDAP query

Thank You

**Comment by jpkessler** [comment]
postfwd supports the configuration options mentioned on postfwd.org. It has no ldap support builtin. You are free to develop a plugin for that.

**Please note that this is not the right place for configuration questions. Please use the contact information at postfwd.org for such terms. Thank you.**
