### ISSUE TITLE
Per "global" limits?

### ISSUE THREAD

**Issue by NuxRo** [postfwd/postfwd#34]
Hi,

I'm trying to enable rate limiting for the whole server, but am I wrong or this is not currently possible with postfwd?

I have managed to rate limit number of emails per day for sasl_username and sender_domain and that's all fine, but what if I wanted to put a limit on the whole server, regardless of which user or domain is sending it?

Say, no more than 200 emails per day from this server.

Regards

**Comment by jpkessler** [comment]
You can use any policy delegation item for rate limits - in your case you could use client_address or client_name for it.

**Please note that this is not the right place for configuration questions. Please use the contact information at postfwd.org for such terms. Thank you.**
